[package]
name = "yazelix-venus"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
accesskit = "=0.24.1"
accesskit_winit = { version = "=0.33.2", default-features = false, features = ["accesskit_unix", "async-io", "rwh_06"] }
eon-workspace-protocol = { git = "https://github.com/Yazelix/eon.git", rev = "7bb50873ae27e09dfebd8a6ca2f8075bac07afe8" }
glyphon = "=0.12.0"
orbit-protocol = { git = "https://github.com/Yazelix/eon-sessions.git", rev = "59975e9176f5caf8b78dc3273e88d9ecbb75dc3f" }
pollster = { version = "=1.0.1", default-features = false }
wgpu = { version = "=30.0.0", default-features = false, features = ["std", "vulkan", "wgsl"] }
winit = { version = "=0.30.13", default-features = false, features = ["rwh_06", "wayland", "wayland-dlopen"] }
wl-clipboard-rs = { version = "=0.9.3", default-features = false }

[patch.crates-io]
winit = { git = "https://github.com/chiyuki0325/winit-0.30.git", rev = "fb45fbf901fbe70cc9a877b5d651d0b60c206b08" }

[profile.release]
lto = "thin"
strip = "debuginfo"
